name: Build

on:
  workflow_dispatch:

  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  pull-requests: read
  contents: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-build
      cancel-in-progress: true
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version
        id: tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: feat!
          MINOR_STRING_TOKEN: feat
          PRERELEASE: ${{ !!github.event.pull_request }}
          PRERELEASE_SUFFIX: prerelease
          VERBOSE: true
  build:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        env:
          VERSION: ${{ needs.get-version.outputs.tag }}
        run: |
          dotnet build --configuration Release --no-restore -p:Version=${VERSION:1}

      - name: Add NuGet source
        env:
          NUGET_USERNAME: ${{ vars.NUGET_USERNAME }}
          NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}
        run: dotnet nuget add source --username ${NUGET_USERNAME} --password ${NUGET_PASSWORD} --store-password-in-clear-text --name nuget "https://nuget.pkg.github.com/${NUGET_USERNAME}/index.json"


      - name: list files
        run: ls -la bin/Release/net9.0

      - name: Publish package
        env:
          VERSION: ${{ needs.get-version.outputs.tag }}
          API_KEY: ${{ secrets.NUGET_PASSWORD }}
        run: dotnet nuget push "bin/Release/net9.0/Sprout.${VERSION:1}.nupkg" --api-key ${API_KEY} --source nuget --skip-duplicate
